# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json* tsconfig.json ./
COPY src ./src
RUN npm install && npm run build

# Runtime image
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built files and dependencies
COPY package.json package-lock.json* ./
COPY --from=builder /app/dist ./dist
RUN npm install --only=production

# Expose no port (stdio transport)
ENTRYPOINT ["node", "dist/server.js"]
